regen

diff --git a/font/adobe-100dpi/configure b/font/adobe-100dpi/configure
--- a/font/adobe-100dpi/configure
+++ b/font/adobe-100dpi/configure
@@ -2099,6 +2099,9 @@ echo "$as_me:$LINENO: checking for MAPS" >&5
 echo $ECHO_N "checking for MAPS... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$MAPS_CFLAGS"; then
+        pkg_cv_MAPS_CFLAGS="$MAPS_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"fontutil\"") >&5
   ($PKG_CONFIG --exists --print-errors "fontutil") 2>&5
@@ -2109,10 +2112,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$MAPS_LIBS"; then
+        pkg_cv_MAPS_LIBS="$MAPS_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"fontutil\"") >&5
   ($PKG_CONFIG --exists --print-errors "fontutil") 2>&5
@@ -2123,38 +2130,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	MAPS_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "fontutil"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        MAPS_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "fontutil"`
+        else
+	        MAPS_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "fontutil"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$MAPS_PKG_ERRORS" 1>&5
+	echo "$MAPS_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (fontutil) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (fontutil) were not met:
+
+$MAPS_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the MAPS_CFLAGS and MAPS_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (fontutil) were not met.
+Alternatively, you may set the environment variables MAPS_CFLAGS
+and MAPS_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (fontutil) were not met:
+
+$MAPS_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the MAPS_CFLAGS and MAPS_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables MAPS_CFLAGS
+and MAPS_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the MAPS_CFLAGS and MAPS_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables MAPS_CFLAGS
+and MAPS_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -2162,9 +2190,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the MAPS_CFLAGS and MAPS_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables MAPS_CFLAGS
+and MAPS_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
