merge xinit 1.0.6

diff --git a/app/xinit/Makefile.in b/app/xinit/Makefile.in
--- a/app/xinit/Makefile.in
+++ b/app/xinit/Makefile.in
@@ -269,6 +269,7 @@ MANDEFS = \
 	-D__miscmansuffix__=$(MISC_MAN_SUFFIX) \
 	-D__XSERVERNAME__=Xorg -D__XCONFIGFILE__=xorg.conf \
 	-D__xinitdir__=$(XINITDIR) \
+	-D__bindir__=$(bindir) \
 	-DSHELL_CMD=$(SHELL_CMD) $(ARCHMANDEFS)
 
 SUFFIXES = .$(APP_MAN_SUFFIX) .man
@@ -292,7 +293,7 @@ SCRIPTDEFS = \
 xinitrc_DATA = xinitrc
 CLEANFILES = xinitrc startx $(appman_DATA)
 EXTRA_DIST = xinitrc.cpp startx.cpp $(appman_PRE)	\
-		startx.cmd xinitrc.cmd xinit.def
+		startx.cmd xinitrc.cmd xinit.def ChangeLog autogen.sh
 
 all: config.h
 	$(MAKE) $(AM_MAKEFLAGS) all-am
@@ -543,6 +544,9 @@ distdir: $(DISTFILES)
 	    || exit 1; \
 	  fi; \
 	done
+	$(MAKE) $(AM_MAKEFLAGS) \
+	  top_distdir="$(top_distdir)" distdir="$(distdir)" \
+	  dist-hook
 	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
 	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
 	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
@@ -727,8 +731,8 @@ uninstall-am: uninstall-appmanDATA uninstall-binPROGRAMS \
 
 .PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
 	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
-	dist-gzip dist-shar dist-tarZ dist-zip distcheck distclean \
-	distclean-compile distclean-generic distclean-hdr \
+	dist-gzip dist-hook dist-shar dist-tarZ dist-zip distcheck \
+	distclean distclean-compile distclean-generic distclean-hdr \
 	distclean-tags distcleancheck distdir distuninstallcheck dvi \
 	dvi-am html html-am info info-am install install-am \
 	install-appmanDATA install-binPROGRAMS install-binSCRIPTS \
@@ -750,6 +754,11 @@ xinitrc: xinitrc.cpp
 
 startx: startx.cpp Makefile
 	$(RAWCPP) $(SCRIPTDEFS) < $(srcdir)/startx.cpp | $(CPP_SED_MAGIC) > $@
+
+ChangeLog:
+	(GIT_DIR=$(top_srcdir)/.git git-log > .changelog.tmp && mv .changelog.tmp ChangeLog; rm -f .changelog.tmp) || (touch ChangeLog; echo 'git directory not found: installing possibly empty changelog.' >&2)
+
+dist-hook: ChangeLog
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
 .NOEXPORT:
