regen

diff --git a/app/xdriinfo/configure b/app/xdriinfo/configure
--- a/app/xdriinfo/configure
+++ b/app/xdriinfo/configure
@@ -3128,6 +3128,9 @@ echo "$as_me:$LINENO: checking for XDRIINFO" >&5
 echo $ECHO_N "checking for XDRIINFO... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XDRIINFO_CFLAGS"; then
+        pkg_cv_XDRIINFO_CFLAGS="$XDRIINFO_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xext x11 glproto\"") >&5
   ($PKG_CONFIG --exists --print-errors "xext x11 glproto") 2>&5
@@ -3138,10 +3141,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XDRIINFO_LIBS"; then
+        pkg_cv_XDRIINFO_LIBS="$XDRIINFO_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xext x11 glproto\"") >&5
   ($PKG_CONFIG --exists --print-errors "xext x11 glproto") 2>&5
@@ -3152,38 +3159,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	XDRIINFO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xext x11 glproto"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        XDRIINFO_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "xext x11 glproto"`
+        else
+	        XDRIINFO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xext x11 glproto"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$XDRIINFO_PKG_ERRORS" 1>&5
+	echo "$XDRIINFO_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (xext x11 glproto) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (xext x11 glproto) were not met:
+
+$XDRIINFO_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XDRIINFO_CFLAGS and XDRIINFO_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (xext x11 glproto) were not met.
+Alternatively, you may set the environment variables XDRIINFO_CFLAGS
+and XDRIINFO_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (xext x11 glproto) were not met:
+
+$XDRIINFO_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XDRIINFO_CFLAGS and XDRIINFO_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables XDRIINFO_CFLAGS
+and XDRIINFO_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XDRIINFO_CFLAGS and XDRIINFO_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XDRIINFO_CFLAGS
+and XDRIINFO_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -3191,9 +3219,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XDRIINFO_CFLAGS and XDRIINFO_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XDRIINFO_CFLAGS
+and XDRIINFO_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
@@ -3346,6 +3374,7 @@ See \`config.log' for more details." >&2;}
 fi
 
 
+LIBS="$LIBS $XDRIINFO_LIBS"
 
 # Make sure we can run config.sub.
 $ac_config_sub sun4 >/dev/null 2>&1 ||
