regen with libtool 1.5.22p10 and metaauto 0.7

diff --git a/lib/fontconfig/configure b/lib/fontconfig/configure
--- a/lib/fontconfig/configure
+++ b/lib/fontconfig/configure
@@ -21862,6 +21862,9 @@ echo "$as_me:$LINENO: checking for LIBXML2" >&5
 echo $ECHO_N "checking for LIBXML2... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$LIBXML2_CFLAGS"; then
+        pkg_cv_LIBXML2_CFLAGS="$LIBXML2_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libxml-2.0 >= 2.6\"") >&5
   ($PKG_CONFIG --exists --print-errors "libxml-2.0 >= 2.6") 2>&5
@@ -21872,10 +21875,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$LIBXML2_LIBS"; then
+        pkg_cv_LIBXML2_LIBS="$LIBXML2_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libxml-2.0 >= 2.6\"") >&5
   ($PKG_CONFIG --exists --print-errors "libxml-2.0 >= 2.6") 2>&5
@@ -21886,38 +21893,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	LIBXML2_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxml-2.0 >= 2.6"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        LIBXML2_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "libxml-2.0 >= 2.6"`
+        else
+	        LIBXML2_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxml-2.0 >= 2.6"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$LIBXML2_PKG_ERRORS" 1>&5
+	echo "$LIBXML2_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (libxml-2.0 >= 2.6) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (libxml-2.0 >= 2.6) were not met:
+
+$LIBXML2_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the LIBXML2_CFLAGS and LIBXML2_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (libxml-2.0 >= 2.6) were not met.
+Alternatively, you may set the environment variables LIBXML2_CFLAGS
+and LIBXML2_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (libxml-2.0 >= 2.6) were not met:
+
+$LIBXML2_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the LIBXML2_CFLAGS and LIBXML2_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables LIBXML2_CFLAGS
+and LIBXML2_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the LIBXML2_CFLAGS and LIBXML2_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables LIBXML2_CFLAGS
+and LIBXML2_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -21925,9 +21953,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the LIBXML2_CFLAGS and LIBXML2_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables LIBXML2_CFLAGS
+and LIBXML2_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
diff --git a/lib/libSM/configure b/lib/libSM/configure
--- a/lib/libSM/configure
+++ b/lib/libSM/configure
@@ -19543,6 +19543,9 @@ echo "$as_me:$LINENO: checking for SM" >&5
 echo $ECHO_N "checking for SM... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$SM_CFLAGS"; then
+        pkg_cv_SM_CFLAGS="$SM_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"ice xproto\"") >&5
   ($PKG_CONFIG --exists --print-errors "ice xproto") 2>&5
@@ -19553,10 +19556,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$SM_LIBS"; then
+        pkg_cv_SM_LIBS="$SM_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"ice xproto\"") >&5
   ($PKG_CONFIG --exists --print-errors "ice xproto") 2>&5
@@ -19567,38 +19574,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	SM_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "ice xproto"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        SM_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "ice xproto"`
+        else
+	        SM_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "ice xproto"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$SM_PKG_ERRORS" 1>&5
+	echo "$SM_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (ice xproto) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (ice xproto) were not met:
+
+$SM_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the SM_CFLAGS and SM_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (ice xproto) were not met.
+Alternatively, you may set the environment variables SM_CFLAGS
+and SM_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (ice xproto) were not met:
+
+$SM_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the SM_CFLAGS and SM_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables SM_CFLAGS
+and SM_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the SM_CFLAGS and SM_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables SM_CFLAGS
+and SM_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -19606,9 +19634,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the SM_CFLAGS and SM_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables SM_CFLAGS
+and SM_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
@@ -19629,6 +19657,9 @@ echo "$as_me:$LINENO: checking for XTRANS" >&5
 echo $ECHO_N "checking for XTRANS... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XTRANS_CFLAGS"; then
+        pkg_cv_XTRANS_CFLAGS="$XTRANS_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xtrans\"") >&5
   ($PKG_CONFIG --exists --print-errors "xtrans") 2>&5
@@ -19639,10 +19670,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XTRANS_LIBS"; then
+        pkg_cv_XTRANS_LIBS="$XTRANS_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xtrans\"") >&5
   ($PKG_CONFIG --exists --print-errors "xtrans") 2>&5
@@ -19653,38 +19688,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	XTRANS_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xtrans"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        XTRANS_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "xtrans"`
+        else
+	        XTRANS_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xtrans"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$XTRANS_PKG_ERRORS" 1>&5
+	echo "$XTRANS_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (xtrans) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (xtrans) were not met:
+
+$XTRANS_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XTRANS_CFLAGS and XTRANS_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (xtrans) were not met.
+Alternatively, you may set the environment variables XTRANS_CFLAGS
+and XTRANS_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (xtrans) were not met:
+
+$XTRANS_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XTRANS_CFLAGS and XTRANS_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables XTRANS_CFLAGS
+and XTRANS_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XTRANS_CFLAGS and XTRANS_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XTRANS_CFLAGS
+and XTRANS_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -19692,9 +19748,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XTRANS_CFLAGS and XTRANS_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XTRANS_CFLAGS
+and XTRANS_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
diff --git a/lib/libX11/configure b/lib/libX11/configure
--- a/lib/libX11/configure
+++ b/lib/libX11/configure
@@ -19717,6 +19717,9 @@ echo "$as_me:$LINENO: checking for XPROTO" >&5
 echo $ECHO_N "checking for XPROTO... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XPROTO_CFLAGS"; then
+        pkg_cv_XPROTO_CFLAGS="$XPROTO_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xproto >= 7.0.6\"") >&5
   ($PKG_CONFIG --exists --print-errors "xproto >= 7.0.6") 2>&5
@@ -19727,10 +19730,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XPROTO_LIBS"; then
+        pkg_cv_XPROTO_LIBS="$XPROTO_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xproto >= 7.0.6\"") >&5
   ($PKG_CONFIG --exists --print-errors "xproto >= 7.0.6") 2>&5
@@ -19741,38 +19748,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	XPROTO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xproto >= 7.0.6"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        XPROTO_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "xproto >= 7.0.6"`
+        else
+	        XPROTO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xproto >= 7.0.6"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$XPROTO_PKG_ERRORS" 1>&5
+	echo "$XPROTO_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (xproto >= 7.0.6) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (xproto >= 7.0.6) were not met:
+
+$XPROTO_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XPROTO_CFLAGS and XPROTO_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (xproto >= 7.0.6) were not met.
+Alternatively, you may set the environment variables XPROTO_CFLAGS
+and XPROTO_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (xproto >= 7.0.6) were not met:
+
+$XPROTO_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XPROTO_CFLAGS and XPROTO_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables XPROTO_CFLAGS
+and XPROTO_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XPROTO_CFLAGS and XPROTO_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XPROTO_CFLAGS
+and XPROTO_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -19780,9 +19808,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XPROTO_CFLAGS and XPROTO_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XPROTO_CFLAGS
+and XPROTO_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
@@ -19805,6 +19833,9 @@ echo "$as_me:$LINENO: checking for XDMCP" >&5
 echo $ECHO_N "checking for XDMCP... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XDMCP_CFLAGS"; then
+        pkg_cv_XDMCP_CFLAGS="$XDMCP_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xdmcp\"") >&5
   ($PKG_CONFIG --exists --print-errors "xdmcp") 2>&5
@@ -19815,10 +19846,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XDMCP_LIBS"; then
+        pkg_cv_XDMCP_LIBS="$XDMCP_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xdmcp\"") >&5
   ($PKG_CONFIG --exists --print-errors "xdmcp") 2>&5
@@ -19829,38 +19864,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	XDMCP_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xdmcp"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        XDMCP_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "xdmcp"`
+        else
+	        XDMCP_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xdmcp"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$XDMCP_PKG_ERRORS" 1>&5
+	echo "$XDMCP_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (xdmcp) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (xdmcp) were not met:
+
+$XDMCP_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XDMCP_CFLAGS and XDMCP_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (xdmcp) were not met.
+Alternatively, you may set the environment variables XDMCP_CFLAGS
+and XDMCP_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (xdmcp) were not met:
+
+$XDMCP_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XDMCP_CFLAGS and XDMCP_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables XDMCP_CFLAGS
+and XDMCP_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XDMCP_CFLAGS and XDMCP_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XDMCP_CFLAGS
+and XDMCP_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -19868,9 +19924,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XDMCP_CFLAGS and XDMCP_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XDMCP_CFLAGS
+and XDMCP_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
@@ -19976,6 +20032,9 @@ echo "$as_me:$LINENO: checking for X11" >&5
 echo $ECHO_N "checking for X11... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$X11_CFLAGS"; then
+        pkg_cv_X11_CFLAGS="$X11_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xextproto xtrans \$X11_REQUIRES\"") >&5
   ($PKG_CONFIG --exists --print-errors "xextproto xtrans $X11_REQUIRES") 2>&5
@@ -19986,10 +20045,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$X11_LIBS"; then
+        pkg_cv_X11_LIBS="$X11_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xextproto xtrans \$X11_REQUIRES\"") >&5
   ($PKG_CONFIG --exists --print-errors "xextproto xtrans $X11_REQUIRES") 2>&5
@@ -20000,38 +20063,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	X11_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xextproto xtrans $X11_REQUIRES"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        X11_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "xextproto xtrans $X11_REQUIRES"`
+        else
+	        X11_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xextproto xtrans $X11_REQUIRES"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$X11_PKG_ERRORS" 1>&5
+	echo "$X11_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (xextproto xtrans $X11_REQUIRES) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (xextproto xtrans $X11_REQUIRES) were not met:
+
+$X11_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the X11_CFLAGS and X11_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (xextproto xtrans $X11_REQUIRES) were not met.
+Alternatively, you may set the environment variables X11_CFLAGS
+and X11_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (xextproto xtrans $X11_REQUIRES) were not met:
+
+$X11_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the X11_CFLAGS and X11_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables X11_CFLAGS
+and X11_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the X11_CFLAGS and X11_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables X11_CFLAGS
+and X11_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -20039,9 +20123,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the X11_CFLAGS and X11_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables X11_CFLAGS
+and X11_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
@@ -22546,6 +22630,9 @@ echo "$as_me:$LINENO: checking for BIGFONT" >&5
 echo $ECHO_N "checking for BIGFONT... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$BIGFONT_CFLAGS"; then
+        pkg_cv_BIGFONT_CFLAGS="$BIGFONT_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xf86bigfontproto\"") >&5
   ($PKG_CONFIG --exists --print-errors "xf86bigfontproto") 2>&5
@@ -22556,10 +22643,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$BIGFONT_LIBS"; then
+        pkg_cv_BIGFONT_LIBS="$BIGFONT_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xf86bigfontproto\"") >&5
   ($PKG_CONFIG --exists --print-errors "xf86bigfontproto") 2>&5
@@ -22570,16 +22661,31 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
-if test $pkg_failed = yes; then
-	BIGFONT_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xf86bigfontproto"`
-	# Put the nasty error message in config.log where it belongs
-	echo "$BIGFONT_PKG_ERRORS" 1>&5
 
-	XF86BIGFONT="no"
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        BIGFONT_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "xf86bigfontproto"`
+        else
+	        BIGFONT_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xf86bigfontproto"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$BIGFONT_PKG_ERRORS" >&5
+
+	echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+                XF86BIGFONT="no"
 elif test $pkg_failed = untried; then
 	XF86BIGFONT="no"
 else
@@ -22718,6 +22824,9 @@ echo "$as_me:$LINENO: checking for XKBPROTO" >&5
 echo $ECHO_N "checking for XKBPROTO... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XKBPROTO_CFLAGS"; then
+        pkg_cv_XKBPROTO_CFLAGS="$XKBPROTO_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"kbproto inputproto\"") >&5
   ($PKG_CONFIG --exists --print-errors "kbproto inputproto") 2>&5
@@ -22728,10 +22837,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XKBPROTO_LIBS"; then
+        pkg_cv_XKBPROTO_LIBS="$XKBPROTO_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"kbproto inputproto\"") >&5
   ($PKG_CONFIG --exists --print-errors "kbproto inputproto") 2>&5
@@ -22742,38 +22855,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	XKBPROTO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "kbproto inputproto"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        XKBPROTO_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "kbproto inputproto"`
+        else
+	        XKBPROTO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "kbproto inputproto"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$XKBPROTO_PKG_ERRORS" 1>&5
+	echo "$XKBPROTO_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (kbproto inputproto) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (kbproto inputproto) were not met:
+
+$XKBPROTO_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XKBPROTO_CFLAGS and XKBPROTO_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (kbproto inputproto) were not met.
+Alternatively, you may set the environment variables XKBPROTO_CFLAGS
+and XKBPROTO_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (kbproto inputproto) were not met:
+
+$XKBPROTO_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XKBPROTO_CFLAGS and XKBPROTO_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables XKBPROTO_CFLAGS
+and XKBPROTO_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XKBPROTO_CFLAGS and XKBPROTO_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XKBPROTO_CFLAGS
+and XKBPROTO_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -22781,9 +22915,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XKBPROTO_CFLAGS and XKBPROTO_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XKBPROTO_CFLAGS
+and XKBPROTO_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
diff --git a/lib/libXRes/configure b/lib/libXRes/configure
--- a/lib/libXRes/configure
+++ b/lib/libXRes/configure
@@ -18672,6 +18672,9 @@ echo "$as_me:$LINENO: checking for XRES" >&5
 echo $ECHO_N "checking for XRES... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XRES_CFLAGS"; then
+        pkg_cv_XRES_CFLAGS="$XRES_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"x11 xext xextproto\"") >&5
   ($PKG_CONFIG --exists --print-errors "x11 xext xextproto") 2>&5
@@ -18682,10 +18685,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XRES_LIBS"; then
+        pkg_cv_XRES_LIBS="$XRES_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"x11 xext xextproto\"") >&5
   ($PKG_CONFIG --exists --print-errors "x11 xext xextproto") 2>&5
@@ -18696,38 +18703,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	XRES_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "x11 xext xextproto"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        XRES_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "x11 xext xextproto"`
+        else
+	        XRES_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "x11 xext xextproto"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$XRES_PKG_ERRORS" 1>&5
+	echo "$XRES_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (x11 xext xextproto) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (x11 xext xextproto) were not met:
+
+$XRES_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XRES_CFLAGS and XRES_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (x11 xext xextproto) were not met.
+Alternatively, you may set the environment variables XRES_CFLAGS
+and XRES_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (x11 xext xextproto) were not met:
+
+$XRES_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XRES_CFLAGS and XRES_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables XRES_CFLAGS
+and XRES_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XRES_CFLAGS and XRES_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XRES_CFLAGS
+and XRES_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -18735,9 +18763,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XRES_CFLAGS and XRES_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XRES_CFLAGS
+and XRES_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
@@ -18763,6 +18791,9 @@ echo "$as_me:$LINENO: checking for RESOURCEEXT" >&5
 echo $ECHO_N "checking for RESOURCEEXT... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$RESOURCEEXT_CFLAGS"; then
+        pkg_cv_RESOURCEEXT_CFLAGS="$RESOURCEEXT_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"resourceproto >= \$RES_VERSION\"") >&5
   ($PKG_CONFIG --exists --print-errors "resourceproto >= $RES_VERSION") 2>&5
@@ -18773,10 +18804,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$RESOURCEEXT_LIBS"; then
+        pkg_cv_RESOURCEEXT_LIBS="$RESOURCEEXT_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"resourceproto >= \$RES_VERSION\"") >&5
   ($PKG_CONFIG --exists --print-errors "resourceproto >= $RES_VERSION") 2>&5
@@ -18787,38 +18822,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	RESOURCEEXT_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "resourceproto >= $RES_VERSION"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        RESOURCEEXT_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "resourceproto >= $RES_VERSION"`
+        else
+	        RESOURCEEXT_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "resourceproto >= $RES_VERSION"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$RESOURCEEXT_PKG_ERRORS" 1>&5
+	echo "$RESOURCEEXT_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (resourceproto >= $RES_VERSION) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (resourceproto >= $RES_VERSION) were not met:
+
+$RESOURCEEXT_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the RESOURCEEXT_CFLAGS and RESOURCEEXT_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (resourceproto >= $RES_VERSION) were not met.
+Alternatively, you may set the environment variables RESOURCEEXT_CFLAGS
+and RESOURCEEXT_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (resourceproto >= $RES_VERSION) were not met:
+
+$RESOURCEEXT_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the RESOURCEEXT_CFLAGS and RESOURCEEXT_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables RESOURCEEXT_CFLAGS
+and RESOURCEEXT_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the RESOURCEEXT_CFLAGS and RESOURCEEXT_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables RESOURCEEXT_CFLAGS
+and RESOURCEEXT_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -18826,9 +18882,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the RESOURCEEXT_CFLAGS and RESOURCEEXT_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables RESOURCEEXT_CFLAGS
+and RESOURCEEXT_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
diff --git a/lib/libXdamage/configure b/lib/libXdamage/configure
--- a/lib/libXdamage/configure
+++ b/lib/libXdamage/configure
@@ -18702,6 +18702,9 @@ echo "$as_me:$LINENO: checking for X" >&5
 echo $ECHO_N "checking for X... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$X_CFLAGS"; then
+        pkg_cv_X_CFLAGS="$X_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"x11\"") >&5
   ($PKG_CONFIG --exists --print-errors "x11") 2>&5
@@ -18712,10 +18715,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$X_LIBS"; then
+        pkg_cv_X_LIBS="$X_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"x11\"") >&5
   ($PKG_CONFIG --exists --print-errors "x11") 2>&5
@@ -18726,16 +18733,31 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
-if test $pkg_failed = yes; then
-	X_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "x11"`
-	# Put the nasty error message in config.log where it belongs
-	echo "$X_PKG_ERRORS" 1>&5
 
-	x_found_with_pkgconfig=no
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        X_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "x11"`
+        else
+	        X_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "x11"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$X_PKG_ERRORS" >&5
+
+	echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+                x_found_with_pkgconfig=no
 elif test $pkg_failed = untried; then
 	x_found_with_pkgconfig=no
 else
@@ -20216,6 +20238,9 @@ echo "$as_me:$LINENO: checking for XDAMAGE" >&5
 echo $ECHO_N "checking for XDAMAGE... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XDAMAGE_CFLAGS"; then
+        pkg_cv_XDAMAGE_CFLAGS="$XDAMAGE_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"damageproto >= \$DAMAGEEXT_VERSION xfixes fixesproto xextproto\"") >&5
   ($PKG_CONFIG --exists --print-errors "damageproto >= $DAMAGEEXT_VERSION xfixes fixesproto xextproto") 2>&5
@@ -20226,10 +20251,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XDAMAGE_LIBS"; then
+        pkg_cv_XDAMAGE_LIBS="$XDAMAGE_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"damageproto >= \$DAMAGEEXT_VERSION xfixes fixesproto xextproto\"") >&5
   ($PKG_CONFIG --exists --print-errors "damageproto >= $DAMAGEEXT_VERSION xfixes fixesproto xextproto") 2>&5
@@ -20240,38 +20269,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	XDAMAGE_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "damageproto >= $DAMAGEEXT_VERSION xfixes fixesproto xextproto"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        XDAMAGE_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "damageproto >= $DAMAGEEXT_VERSION xfixes fixesproto xextproto"`
+        else
+	        XDAMAGE_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "damageproto >= $DAMAGEEXT_VERSION xfixes fixesproto xextproto"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$XDAMAGE_PKG_ERRORS" 1>&5
+	echo "$XDAMAGE_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (damageproto >= $DAMAGEEXT_VERSION xfixes fixesproto xextproto) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (damageproto >= $DAMAGEEXT_VERSION xfixes fixesproto xextproto) were not met:
+
+$XDAMAGE_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XDAMAGE_CFLAGS and XDAMAGE_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (damageproto >= $DAMAGEEXT_VERSION xfixes fixesproto xextproto) were not met.
+Alternatively, you may set the environment variables XDAMAGE_CFLAGS
+and XDAMAGE_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (damageproto >= $DAMAGEEXT_VERSION xfixes fixesproto xextproto) were not met:
+
+$XDAMAGE_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XDAMAGE_CFLAGS and XDAMAGE_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables XDAMAGE_CFLAGS
+and XDAMAGE_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XDAMAGE_CFLAGS and XDAMAGE_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XDAMAGE_CFLAGS
+and XDAMAGE_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -20279,9 +20329,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XDAMAGE_CFLAGS and XDAMAGE_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XDAMAGE_CFLAGS
+and XDAMAGE_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
diff --git a/lib/libXft/configure b/lib/libXft/configure
--- a/lib/libXft/configure
+++ b/lib/libXft/configure
@@ -18720,6 +18720,9 @@ echo "$as_me:$LINENO: checking for XRENDER" >&5
 echo $ECHO_N "checking for XRENDER... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XRENDER_CFLAGS"; then
+        pkg_cv_XRENDER_CFLAGS="$XRENDER_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xrender >= 0.8.2\"") >&5
   ($PKG_CONFIG --exists --print-errors "xrender >= 0.8.2") 2>&5
@@ -18730,10 +18733,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XRENDER_LIBS"; then
+        pkg_cv_XRENDER_LIBS="$XRENDER_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xrender >= 0.8.2\"") >&5
   ($PKG_CONFIG --exists --print-errors "xrender >= 0.8.2") 2>&5
@@ -18744,16 +18751,31 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
-if test $pkg_failed = yes; then
-	XRENDER_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xrender >= 0.8.2"`
-	# Put the nasty error message in config.log where it belongs
-	echo "$XRENDER_PKG_ERRORS" 1>&5
 
-	xrender_found_with_pkgconfig=no
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        XRENDER_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "xrender >= 0.8.2"`
+        else
+	        XRENDER_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xrender >= 0.8.2"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$XRENDER_PKG_ERRORS" >&5
+
+	echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+                xrender_found_with_pkgconfig=no
 elif test $pkg_failed = untried; then
 	xrender_found_with_pkgconfig=no
 else
@@ -18771,6 +18793,9 @@ echo "$as_me:$LINENO: checking for XRENDER" >&5
 echo $ECHO_N "checking for XRENDER... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XRENDER_CFLAGS"; then
+        pkg_cv_XRENDER_CFLAGS="$XRENDER_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xrender >= 0\"") >&5
   ($PKG_CONFIG --exists --print-errors "xrender >= 0") 2>&5
@@ -18781,10 +18806,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XRENDER_LIBS"; then
+        pkg_cv_XRENDER_LIBS="$XRENDER_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xrender >= 0\"") >&5
   ($PKG_CONFIG --exists --print-errors "xrender >= 0") 2>&5
@@ -18795,16 +18824,31 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
-if test $pkg_failed = yes; then
-	XRENDER_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xrender >= 0"`
-	# Put the nasty error message in config.log where it belongs
-	echo "$XRENDER_PKG_ERRORS" 1>&5
 
-	old_xrender_found_with_pkgconfig=no
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        XRENDER_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "xrender >= 0"`
+        else
+	        XRENDER_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xrender >= 0"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$XRENDER_PKG_ERRORS" >&5
+
+	echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+                old_xrender_found_with_pkgconfig=no
 elif test $pkg_failed = untried; then
 	old_xrender_found_with_pkgconfig=no
 else
@@ -19347,6 +19391,9 @@ echo "$as_me:$LINENO: checking for FREETYPE" >&5
 echo $ECHO_N "checking for FREETYPE... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$FREETYPE_CFLAGS"; then
+        pkg_cv_FREETYPE_CFLAGS="$FREETYPE_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"freetype2\"") >&5
   ($PKG_CONFIG --exists --print-errors "freetype2") 2>&5
@@ -19357,10 +19404,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$FREETYPE_LIBS"; then
+        pkg_cv_FREETYPE_LIBS="$FREETYPE_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"freetype2\"") >&5
   ($PKG_CONFIG --exists --print-errors "freetype2") 2>&5
@@ -19371,16 +19422,31 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
-if test $pkg_failed = yes; then
-	FREETYPE_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "freetype2"`
-	# Put the nasty error message in config.log where it belongs
-	echo "$FREETYPE_PKG_ERRORS" 1>&5
 
-	freetype_config=yes
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        FREETYPE_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "freetype2"`
+        else
+	        FREETYPE_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "freetype2"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$FREETYPE_PKG_ERRORS" >&5
+
+	echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+                freetype_config=yes
 elif test $pkg_failed = untried; then
 	freetype_config=yes
 else
@@ -19454,6 +19520,9 @@ echo "$as_me:$LINENO: checking for FONTCONFIG" >&5
 echo $ECHO_N "checking for FONTCONFIG... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$FONTCONFIG_CFLAGS"; then
+        pkg_cv_FONTCONFIG_CFLAGS="$FONTCONFIG_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"fontconfig >= 2.2\"") >&5
   ($PKG_CONFIG --exists --print-errors "fontconfig >= 2.2") 2>&5
@@ -19464,10 +19533,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$FONTCONFIG_LIBS"; then
+        pkg_cv_FONTCONFIG_LIBS="$FONTCONFIG_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"fontconfig >= 2.2\"") >&5
   ($PKG_CONFIG --exists --print-errors "fontconfig >= 2.2") 2>&5
@@ -19478,38 +19551,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	FONTCONFIG_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "fontconfig >= 2.2"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        FONTCONFIG_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "fontconfig >= 2.2"`
+        else
+	        FONTCONFIG_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "fontconfig >= 2.2"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$FONTCONFIG_PKG_ERRORS" 1>&5
+	echo "$FONTCONFIG_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (fontconfig >= 2.2) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (fontconfig >= 2.2) were not met:
+
+$FONTCONFIG_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the FONTCONFIG_CFLAGS and FONTCONFIG_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (fontconfig >= 2.2) were not met.
+Alternatively, you may set the environment variables FONTCONFIG_CFLAGS
+and FONTCONFIG_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (fontconfig >= 2.2) were not met:
+
+$FONTCONFIG_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the FONTCONFIG_CFLAGS and FONTCONFIG_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables FONTCONFIG_CFLAGS
+and FONTCONFIG_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the FONTCONFIG_CFLAGS and FONTCONFIG_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables FONTCONFIG_CFLAGS
+and FONTCONFIG_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -19517,9 +19611,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the FONTCONFIG_CFLAGS and FONTCONFIG_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables FONTCONFIG_CFLAGS
+and FONTCONFIG_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
diff --git a/lib/libXi/configure b/lib/libXi/configure
--- a/lib/libXi/configure
+++ b/lib/libXi/configure
@@ -18687,6 +18687,9 @@ echo "$as_me:$LINENO: checking for XI" >&5
 echo $ECHO_N "checking for XI... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XI_CFLAGS"; then
+        pkg_cv_XI_CFLAGS="$XI_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xproto x11 xextproto xext inputproto\"") >&5
   ($PKG_CONFIG --exists --print-errors "xproto x11 xextproto xext inputproto") 2>&5
@@ -18697,10 +18700,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XI_LIBS"; then
+        pkg_cv_XI_LIBS="$XI_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xproto x11 xextproto xext inputproto\"") >&5
   ($PKG_CONFIG --exists --print-errors "xproto x11 xextproto xext inputproto") 2>&5
@@ -18711,38 +18718,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	XI_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xproto x11 xextproto xext inputproto"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        XI_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "xproto x11 xextproto xext inputproto"`
+        else
+	        XI_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xproto x11 xextproto xext inputproto"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$XI_PKG_ERRORS" 1>&5
+	echo "$XI_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (xproto x11 xextproto xext inputproto) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (xproto x11 xextproto xext inputproto) were not met:
+
+$XI_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XI_CFLAGS and XI_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (xproto x11 xextproto xext inputproto) were not met.
+Alternatively, you may set the environment variables XI_CFLAGS
+and XI_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (xproto x11 xextproto xext inputproto) were not met:
+
+$XI_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XI_CFLAGS and XI_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables XI_CFLAGS
+and XI_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XI_CFLAGS and XI_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XI_CFLAGS
+and XI_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -18750,9 +18778,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XI_CFLAGS and XI_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XI_CFLAGS
+and XI_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
diff --git a/lib/libXmu/configure b/lib/libXmu/configure
--- a/lib/libXmu/configure
+++ b/lib/libXmu/configure
@@ -19542,6 +19542,9 @@ echo "$as_me:$LINENO: checking for XMU" >&5
 echo $ECHO_N "checking for XMU... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XMU_CFLAGS"; then
+        pkg_cv_XMU_CFLAGS="$XMU_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xt xext xextproto\"") >&5
   ($PKG_CONFIG --exists --print-errors "xt xext xextproto") 2>&5
@@ -19552,10 +19555,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XMU_LIBS"; then
+        pkg_cv_XMU_LIBS="$XMU_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xt xext xextproto\"") >&5
   ($PKG_CONFIG --exists --print-errors "xt xext xextproto") 2>&5
@@ -19566,38 +19573,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	XMU_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xt xext xextproto"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        XMU_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "xt xext xextproto"`
+        else
+	        XMU_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xt xext xextproto"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$XMU_PKG_ERRORS" 1>&5
+	echo "$XMU_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (xt xext xextproto) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (xt xext xextproto) were not met:
+
+$XMU_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XMU_CFLAGS and XMU_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (xt xext xextproto) were not met.
+Alternatively, you may set the environment variables XMU_CFLAGS
+and XMU_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (xt xext xextproto) were not met:
+
+$XMU_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XMU_CFLAGS and XMU_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables XMU_CFLAGS
+and XMU_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XMU_CFLAGS and XMU_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XMU_CFLAGS
+and XMU_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -19605,9 +19633,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XMU_CFLAGS and XMU_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XMU_CFLAGS
+and XMU_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
@@ -19628,6 +19656,9 @@ echo "$as_me:$LINENO: checking for XMUU" >&5
 echo $ECHO_N "checking for XMUU... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XMUU_CFLAGS"; then
+        pkg_cv_XMUU_CFLAGS="$XMUU_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"x11\"") >&5
   ($PKG_CONFIG --exists --print-errors "x11") 2>&5
@@ -19638,10 +19669,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XMUU_LIBS"; then
+        pkg_cv_XMUU_LIBS="$XMUU_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"x11\"") >&5
   ($PKG_CONFIG --exists --print-errors "x11") 2>&5
@@ -19652,38 +19687,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	XMUU_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "x11"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        XMUU_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "x11"`
+        else
+	        XMUU_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "x11"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$XMUU_PKG_ERRORS" 1>&5
+	echo "$XMUU_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (x11) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (x11) were not met:
+
+$XMUU_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XMUU_CFLAGS and XMUU_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (x11) were not met.
+Alternatively, you may set the environment variables XMUU_CFLAGS
+and XMUU_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (x11) were not met:
+
+$XMUU_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XMUU_CFLAGS and XMUU_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables XMUU_CFLAGS
+and XMUU_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XMUU_CFLAGS and XMUU_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XMUU_CFLAGS
+and XMUU_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -19691,9 +19747,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XMUU_CFLAGS and XMUU_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XMUU_CFLAGS
+and XMUU_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
diff --git a/lib/libXprintUtil/configure b/lib/libXprintUtil/configure
--- a/lib/libXprintUtil/configure
+++ b/lib/libXprintUtil/configure
@@ -18687,6 +18687,9 @@ echo "$as_me:$LINENO: checking for XPRINTUTIL" >&5
 echo $ECHO_N "checking for XPRINTUTIL... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XPRINTUTIL_CFLAGS"; then
+        pkg_cv_XPRINTUTIL_CFLAGS="$XPRINTUTIL_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"x11 xp xt printproto xau\"") >&5
   ($PKG_CONFIG --exists --print-errors "x11 xp xt printproto xau") 2>&5
@@ -18697,10 +18700,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XPRINTUTIL_LIBS"; then
+        pkg_cv_XPRINTUTIL_LIBS="$XPRINTUTIL_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"x11 xp xt printproto xau\"") >&5
   ($PKG_CONFIG --exists --print-errors "x11 xp xt printproto xau") 2>&5
@@ -18711,38 +18718,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	XPRINTUTIL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "x11 xp xt printproto xau"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        XPRINTUTIL_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "x11 xp xt printproto xau"`
+        else
+	        XPRINTUTIL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "x11 xp xt printproto xau"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$XPRINTUTIL_PKG_ERRORS" 1>&5
+	echo "$XPRINTUTIL_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (x11 xp xt printproto xau) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (x11 xp xt printproto xau) were not met:
+
+$XPRINTUTIL_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XPRINTUTIL_CFLAGS and XPRINTUTIL_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (x11 xp xt printproto xau) were not met.
+Alternatively, you may set the environment variables XPRINTUTIL_CFLAGS
+and XPRINTUTIL_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (x11 xp xt printproto xau) were not met:
+
+$XPRINTUTIL_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XPRINTUTIL_CFLAGS and XPRINTUTIL_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables XPRINTUTIL_CFLAGS
+and XPRINTUTIL_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XPRINTUTIL_CFLAGS and XPRINTUTIL_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XPRINTUTIL_CFLAGS
+and XPRINTUTIL_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -18750,9 +18778,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XPRINTUTIL_CFLAGS and XPRINTUTIL_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XPRINTUTIL_CFLAGS
+and XPRINTUTIL_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
diff --git a/lib/libXrandr/configure b/lib/libXrandr/configure
--- a/lib/libXrandr/configure
+++ b/lib/libXrandr/configure
@@ -18698,6 +18698,9 @@ echo "$as_me:$LINENO: checking for X" >&5
 echo $ECHO_N "checking for X... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$X_CFLAGS"; then
+        pkg_cv_X_CFLAGS="$X_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"x11\"") >&5
   ($PKG_CONFIG --exists --print-errors "x11") 2>&5
@@ -18708,10 +18711,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$X_LIBS"; then
+        pkg_cv_X_LIBS="$X_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"x11\"") >&5
   ($PKG_CONFIG --exists --print-errors "x11") 2>&5
@@ -18722,38 +18729,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	X_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "x11"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        X_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "x11"`
+        else
+	        X_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "x11"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$X_PKG_ERRORS" 1>&5
+	echo "$X_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (x11) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (x11) were not met:
+
+$X_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the X_CFLAGS and X_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (x11) were not met.
+Alternatively, you may set the environment variables X_CFLAGS
+and X_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (x11) were not met:
+
+$X_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the X_CFLAGS and X_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables X_CFLAGS
+and X_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the X_CFLAGS and X_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables X_CFLAGS
+and X_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -18761,9 +18789,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the X_CFLAGS and X_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables X_CFLAGS
+and X_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
@@ -18789,6 +18817,9 @@ echo "$as_me:$LINENO: checking for RANDR" >&5
 echo $ECHO_N "checking for RANDR... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$RANDR_CFLAGS"; then
+        pkg_cv_RANDR_CFLAGS="$RANDR_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"randrproto >= \$RANDR_VERSION xext xextproto xrender renderproto\"") >&5
   ($PKG_CONFIG --exists --print-errors "randrproto >= $RANDR_VERSION xext xextproto xrender renderproto") 2>&5
@@ -18799,10 +18830,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$RANDR_LIBS"; then
+        pkg_cv_RANDR_LIBS="$RANDR_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"randrproto >= \$RANDR_VERSION xext xextproto xrender renderproto\"") >&5
   ($PKG_CONFIG --exists --print-errors "randrproto >= $RANDR_VERSION xext xextproto xrender renderproto") 2>&5
@@ -18813,38 +18848,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	RANDR_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "randrproto >= $RANDR_VERSION xext xextproto xrender renderproto"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        RANDR_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "randrproto >= $RANDR_VERSION xext xextproto xrender renderproto"`
+        else
+	        RANDR_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "randrproto >= $RANDR_VERSION xext xextproto xrender renderproto"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$RANDR_PKG_ERRORS" 1>&5
+	echo "$RANDR_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (randrproto >= $RANDR_VERSION xext xextproto xrender renderproto) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (randrproto >= $RANDR_VERSION xext xextproto xrender renderproto) were not met:
+
+$RANDR_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the RANDR_CFLAGS and RANDR_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (randrproto >= $RANDR_VERSION xext xextproto xrender renderproto) were not met.
+Alternatively, you may set the environment variables RANDR_CFLAGS
+and RANDR_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (randrproto >= $RANDR_VERSION xext xextproto xrender renderproto) were not met:
+
+$RANDR_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the RANDR_CFLAGS and RANDR_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables RANDR_CFLAGS
+and RANDR_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the RANDR_CFLAGS and RANDR_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables RANDR_CFLAGS
+and RANDR_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -18852,9 +18908,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the RANDR_CFLAGS and RANDR_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables RANDR_CFLAGS
+and RANDR_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
diff --git a/lib/libXrender/configure b/lib/libXrender/configure
--- a/lib/libXrender/configure
+++ b/lib/libXrender/configure
@@ -18698,6 +18698,9 @@ echo "$as_me:$LINENO: checking for X" >&5
 echo $ECHO_N "checking for X... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$X_CFLAGS"; then
+        pkg_cv_X_CFLAGS="$X_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"x11\"") >&5
   ($PKG_CONFIG --exists --print-errors "x11") 2>&5
@@ -18708,10 +18711,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$X_LIBS"; then
+        pkg_cv_X_LIBS="$X_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"x11\"") >&5
   ($PKG_CONFIG --exists --print-errors "x11") 2>&5
@@ -18722,38 +18729,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	X_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "x11"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        X_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "x11"`
+        else
+	        X_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "x11"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$X_PKG_ERRORS" 1>&5
+	echo "$X_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (x11) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (x11) were not met:
+
+$X_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the X_CFLAGS and X_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (x11) were not met.
+Alternatively, you may set the environment variables X_CFLAGS
+and X_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (x11) were not met:
+
+$X_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the X_CFLAGS and X_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables X_CFLAGS
+and X_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the X_CFLAGS and X_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables X_CFLAGS
+and X_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -18761,9 +18789,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the X_CFLAGS and X_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables X_CFLAGS
+and X_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
@@ -18798,6 +18826,9 @@ echo "$as_me:$LINENO: checking for RENDER" >&5
 echo $ECHO_N "checking for RENDER... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$RENDER_CFLAGS"; then
+        pkg_cv_RENDER_CFLAGS="$RENDER_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"renderproto >= \$RENDER_VERSION\"") >&5
   ($PKG_CONFIG --exists --print-errors "renderproto >= $RENDER_VERSION") 2>&5
@@ -18808,10 +18839,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$RENDER_LIBS"; then
+        pkg_cv_RENDER_LIBS="$RENDER_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"renderproto >= \$RENDER_VERSION\"") >&5
   ($PKG_CONFIG --exists --print-errors "renderproto >= $RENDER_VERSION") 2>&5
@@ -18822,38 +18857,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	RENDER_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "renderproto >= $RENDER_VERSION"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        RENDER_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "renderproto >= $RENDER_VERSION"`
+        else
+	        RENDER_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "renderproto >= $RENDER_VERSION"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$RENDER_PKG_ERRORS" 1>&5
+	echo "$RENDER_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (renderproto >= $RENDER_VERSION) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (renderproto >= $RENDER_VERSION) were not met:
+
+$RENDER_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the RENDER_CFLAGS and RENDER_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (renderproto >= $RENDER_VERSION) were not met.
+Alternatively, you may set the environment variables RENDER_CFLAGS
+and RENDER_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (renderproto >= $RENDER_VERSION) were not met:
+
+$RENDER_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the RENDER_CFLAGS and RENDER_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables RENDER_CFLAGS
+and RENDER_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the RENDER_CFLAGS and RENDER_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables RENDER_CFLAGS
+and RENDER_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -18861,9 +18917,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the RENDER_CFLAGS and RENDER_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables RENDER_CFLAGS
+and RENDER_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
diff --git a/lib/libXtst/configure b/lib/libXtst/configure
--- a/lib/libXtst/configure
+++ b/lib/libXtst/configure
@@ -18685,6 +18685,9 @@ echo "$as_me:$LINENO: checking for XTST" >&5
 echo $ECHO_N "checking for XTST... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XTST_CFLAGS"; then
+        pkg_cv_XTST_CFLAGS="$XTST_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"x11 xext recordproto xextproto inputproto\"") >&5
   ($PKG_CONFIG --exists --print-errors "x11 xext recordproto xextproto inputproto") 2>&5
@@ -18695,10 +18698,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$XTST_LIBS"; then
+        pkg_cv_XTST_LIBS="$XTST_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"x11 xext recordproto xextproto inputproto\"") >&5
   ($PKG_CONFIG --exists --print-errors "x11 xext recordproto xextproto inputproto") 2>&5
@@ -18709,38 +18716,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	XTST_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "x11 xext recordproto xextproto inputproto"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        XTST_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "x11 xext recordproto xextproto inputproto"`
+        else
+	        XTST_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "x11 xext recordproto xextproto inputproto"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$XTST_PKG_ERRORS" 1>&5
+	echo "$XTST_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (x11 xext recordproto xextproto inputproto) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (x11 xext recordproto xextproto inputproto) were not met:
+
+$XTST_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XTST_CFLAGS and XTST_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (x11 xext recordproto xextproto inputproto) were not met.
+Alternatively, you may set the environment variables XTST_CFLAGS
+and XTST_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (x11 xext recordproto xextproto inputproto) were not met:
+
+$XTST_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the XTST_CFLAGS and XTST_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables XTST_CFLAGS
+and XTST_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XTST_CFLAGS and XTST_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XTST_CFLAGS
+and XTST_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -18748,9 +18776,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the XTST_CFLAGS and XTST_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables XTST_CFLAGS
+and XTST_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
