regen

diff --git a/lib/libfontenc/Makefile.in b/lib/libfontenc/Makefile.in
--- a/lib/libfontenc/Makefile.in
+++ b/lib/libfontenc/Makefile.in
@@ -477,6 +477,9 @@ distdir: $(DISTFILES)
 	      || exit 1; \
 	  fi; \
 	done
+	$(MAKE) $(AM_MAKEFLAGS) \
+	  top_distdir="$(top_distdir)" distdir="$(distdir)" \
+	  dist-hook
 	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
 	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
 	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
@@ -662,7 +665,7 @@ uninstall-info: uninstall-info-recursive
 .PHONY: $(RECURSIVE_TARGETS) CTAGS GTAGS all all-am am--refresh check \
 	check-am clean clean-generic clean-libtool clean-recursive \
 	ctags ctags-recursive dist dist-all dist-bzip2 dist-gzip \
-	dist-shar dist-tarZ dist-zip distcheck distclean \
+	dist-hook dist-shar dist-tarZ dist-zip distcheck distclean \
 	distclean-generic distclean-hdr distclean-libtool \
 	distclean-recursive distclean-tags distcleancheck distdir \
 	distuninstallcheck dvi dvi-am html html-am info info-am \
@@ -676,9 +679,10 @@ uninstall-info: uninstall-info-recursive
 	uninstall uninstall-am uninstall-info-am \
 	uninstall-pkgconfigDATA
 
-ChangeLog: FORCE
-	git-log > ChangeLog
-FORCE:
+ChangeLog:
+	(GIT_DIR=$(top_srcdir)/.git git-log > .changelog.tmp && mv .changelog.tmp ChangeLog; rm -f .changelog.tmp) || (touch ChangeLog; echo 'git directory not found: installing possibly empty changelog.' >&2)
+
+dist-hook: ChangeLog
 
 @LINT_TRUE@lint:
 @LINT_TRUE@	(cd src && $(MAKE) $(MFLAGS) lint)
diff --git a/proto/x11proto/Makefile.in b/proto/x11proto/Makefile.in
--- a/proto/x11proto/Makefile.in
+++ b/proto/x11proto/Makefile.in
@@ -61,11 +61,13 @@ am__vpath_adj = case $$p in \
     *) f=$$p;; \
   esac;
 am__strip_dir = `echo $$p | sed -e 's|^.*/||'`;
-am__installdirs = "$(DESTDIR)$(pkgconfigdir)" "$(DESTDIR)$(xprotodir)"
+am__installdirs = "$(DESTDIR)$(pkgconfigdir)" "$(DESTDIR)$(xprotodir)" \
+	"$(DESTDIR)$(xprotodir)"
 pkgconfigDATA_INSTALL = $(INSTALL_DATA)
 DATA = $(pkgconfig_DATA)
+nodist_xprotoHEADERS_INSTALL = $(INSTALL_HEADER)
 xprotoHEADERS_INSTALL = $(INSTALL_HEADER)
-HEADERS = $(xproto_HEADERS)
+HEADERS = $(nodist_xproto_HEADERS) $(xproto_HEADERS)
 ETAGS = etags
 CTAGS = ctags
 DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
@@ -170,14 +172,12 @@ xproto_HEADERS = \
 	Xatom.h \
 	Xdefs.h \
 	XF86keysym.h \
-	Xfuncproto.h \
 	Xfuncs.h \
 	X.h \
 	Xmd.h \
 	Xosdefs.h \
 	Xos.h \
 	Xos_r.h \
-	Xpoll.h \
 	Xproto.h \
 	Xprotostr.h \
 	Xthreads.h \
@@ -185,6 +185,10 @@ xproto_HEADERS = \
 	XWDFile.h \
 	Xwindows.h \
 	Xwinsock.h
+
+nodist_xproto_HEADERS = \
+	Xfuncproto.h \
+	Xpoll.h
 
 pkgconfigdir = $(libdir)/pkgconfig
 pkgconfig_DATA = xproto.pc
@@ -275,6 +279,23 @@ uninstall-pkgconfigDATA:
 	  f=$(am__strip_dir) \
 	  echo " rm -f '$(DESTDIR)$(pkgconfigdir)/$$f'"; \
 	  rm -f "$(DESTDIR)$(pkgconfigdir)/$$f"; \
+	done
+install-nodist_xprotoHEADERS: $(nodist_xproto_HEADERS)
+	@$(NORMAL_INSTALL)
+	test -z "$(xprotodir)" || $(mkdir_p) "$(DESTDIR)$(xprotodir)"
+	@list='$(nodist_xproto_HEADERS)'; for p in $$list; do \
+	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
+	  f=$(am__strip_dir) \
+	  echo " $(nodist_xprotoHEADERS_INSTALL) '$$d$$p' '$(DESTDIR)$(xprotodir)/$$f'"; \
+	  $(nodist_xprotoHEADERS_INSTALL) "$$d$$p" "$(DESTDIR)$(xprotodir)/$$f"; \
+	done
+
+uninstall-nodist_xprotoHEADERS:
+	@$(NORMAL_UNINSTALL)
+	@list='$(nodist_xproto_HEADERS)'; for p in $$list; do \
+	  f=$(am__strip_dir) \
+	  echo " rm -f '$(DESTDIR)$(xprotodir)/$$f'"; \
+	  rm -f "$(DESTDIR)$(xprotodir)/$$f"; \
 	done
 install-xprotoHEADERS: $(xproto_HEADERS)
 	@$(NORMAL_INSTALL)
@@ -476,7 +497,7 @@ check-am: all-am
 check: check-am
 all-am: Makefile $(DATA) $(HEADERS) do-not-use-config.h Xfuncproto.h
 installdirs:
-	for dir in "$(DESTDIR)$(pkgconfigdir)" "$(DESTDIR)$(xprotodir)"; do \
+	for dir in "$(DESTDIR)$(pkgconfigdir)" "$(DESTDIR)$(xprotodir)" "$(DESTDIR)$(xprotodir)"; do \
 	  test -z "$$dir" || $(mkdir_p) "$$dir"; \
 	done
 install: install-am
@@ -523,7 +544,8 @@ info: info-am
 
 info-am:
 
-install-data-am: install-pkgconfigDATA install-xprotoHEADERS
+install-data-am: install-nodist_xprotoHEADERS install-pkgconfigDATA \
+	install-xprotoHEADERS
 
 install-exec-am:
 
@@ -551,8 +573,8 @@ ps: ps-am
 
 ps-am:
 
-uninstall-am: uninstall-info-am uninstall-pkgconfigDATA \
-	uninstall-xprotoHEADERS
+uninstall-am: uninstall-info-am uninstall-nodist_xprotoHEADERS \
+	uninstall-pkgconfigDATA uninstall-xprotoHEADERS
 
 .PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
 	clean-generic ctags dist dist-all dist-bzip2 dist-gzip \
@@ -561,18 +583,19 @@ uninstall-am: uninstall-info-am uninstall-pkgconfigDATA \
 	distdir distuninstallcheck dvi dvi-am html html-am info \
 	info-am install install-am install-data install-data-am \
 	install-exec install-exec-am install-info install-info-am \
-	install-man install-pkgconfigDATA install-strip \
-	install-xprotoHEADERS installcheck installcheck-am installdirs \
-	maintainer-clean maintainer-clean-generic mostlyclean \
-	mostlyclean-generic pdf pdf-am ps ps-am tags uninstall \
-	uninstall-am uninstall-info-am uninstall-pkgconfigDATA \
+	install-man install-nodist_xprotoHEADERS install-pkgconfigDATA \
+	install-strip install-xprotoHEADERS installcheck \
+	installcheck-am installdirs maintainer-clean \
+	maintainer-clean-generic mostlyclean mostlyclean-generic pdf \
+	pdf-am ps ps-am tags uninstall uninstall-am uninstall-info-am \
+	uninstall-nodist_xprotoHEADERS uninstall-pkgconfigDATA \
 	uninstall-xprotoHEADERS
 
 
 .PHONY: ChangeLog
 
 ChangeLog:
-	(cd $(srcdir) && git-log > ChangeLog )
+	(GIT_DIR=$(top_srcdir)/.git git-log > .changelog.tmp && mv .changelog.tmp ChangeLog; rm -f .changelog.tmp) || (touch ChangeLog; echo 'git directory not found: installing possibly empty changelog.' >&2)
 
 dist-hook: ChangeLog
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
