Update to xfree86-type1-1.0.1.

diff --git a/font/xfree86-type1/Makefile.in b/font/xfree86-type1/Makefile.in
--- a/font/xfree86-type1/Makefile.in
+++ b/font/xfree86-type1/Makefile.in
@@ -155,7 +155,8 @@ FONT_FILES = \
 
 fontdir = @FONTDIR@
 font_DATA = $(FONT_FILES)
-EXTRA_DIST = $(FONT_FILES) autogen.sh
+EXTRA_DIST = $(FONT_FILES) autogen.sh ChangeLog
+MAINTAINERCLEANFILES = ChangeLog
 all: all-am
 
 .SUFFIXES:
@@ -246,6 +247,9 @@ distdir: $(DISTFILES)
 	    || exit 1; \
 	  fi; \
 	done
+	$(MAKE) $(AM_MAKEFLAGS) \
+	  top_distdir="$(top_distdir)" distdir="$(distdir)" \
+	  dist-hook
 	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
 	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
 	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
@@ -365,6 +369,7 @@ distclean-generic:
 maintainer-clean-generic:
 	@echo "This command is intended for maintainers to use"
 	@echo "it deletes files that may require special tools to rebuild."
+	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
 clean: clean-am
 
 clean-am: clean-generic mostlyclean-am
@@ -417,10 +422,10 @@ ps-am:
 uninstall-am: uninstall-fontDATA uninstall-info-am
 
 .PHONY: all all-am am--refresh check check-am clean clean-generic dist \
-	dist-all dist-bzip2 dist-gzip dist-shar dist-tarZ dist-zip \
-	distcheck distclean distclean-generic distcleancheck distdir \
-	distuninstallcheck dvi dvi-am html html-am info info-am \
-	install install-am install-data install-data-am \
+	dist-all dist-bzip2 dist-gzip dist-hook dist-shar dist-tarZ \
+	dist-zip distcheck distclean distclean-generic distcleancheck \
+	distdir distuninstallcheck dvi dvi-am html html-am info \
+	info-am install install-am install-data install-data-am \
 	install-data-hook install-exec install-exec-am \
 	install-fontDATA install-info install-info-am install-man \
 	install-strip installcheck installcheck-am installdirs \
@@ -438,6 +443,13 @@ install-data-hook:
 
 distuninstallcheck:
 	@:
+
+.PHONY: ChangeLog
+
+ChangeLog:
+	(GIT_DIR=$(top_srcdir)/.git git-log > .changelog.tmp && mv .changelog.tmp ChangeLog; rm -f .changelog.tmp) || (touch ChangeLog; echo 'git directory not found: installing possibly empty changelog.' >&2)
+
+dist-hook: ChangeLog
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
 .NOEXPORT:
