xwd 1.0.2

diff --git a/app/xwd/Makefile.in b/app/xwd/Makefile.in
--- a/app/xwd/Makefile.in
+++ b/app/xwd/Makefile.in
@@ -77,8 +77,8 @@ CONFIG_CLEAN_FILES =
 am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(appmandir)"
 binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
 PROGRAMS = $(bin_PROGRAMS)
-am_xwd_OBJECTS = xwd-dsimple.$(OBJEXT) xwd-list.$(OBJEXT) \
-	xwd-multiVis.$(OBJEXT) xwd-xwd.$(OBJEXT)
+am_xwd_OBJECTS = xwd-clientwin.$(OBJEXT) xwd-dsimple.$(OBJEXT) \
+	xwd-list.$(OBJEXT) xwd-multiVis.$(OBJEXT) xwd-xwd.$(OBJEXT)
 xwd_OBJECTS = $(am_xwd_OBJECTS)
 am__DEPENDENCIES_1 =
 xwd_DEPENDENCIES = $(am__DEPENDENCIES_1)
@@ -211,6 +211,8 @@ target_alias = @target_alias@
 xwd_CFLAGS = $(XWD_CFLAGS)
 xwd_LDADD = $(XWD_LIBS)
 xwd_SOURCES = \
+        clientwin.c \
+        clientwin.h \
         dsimple.c \
         dsimple.h \
         list.c \
@@ -225,7 +227,7 @@ appman_PRE = \
 
 appmandir = $(APP_MAN_DIR)
 appman_DATA = $(appman_PRE:man=@APP_MAN_SUFFIX@)
-EXTRA_DIST = $(appman_PRE)
+EXTRA_DIST = $(appman_PRE) ChangeLog
 CLEANFILES = $(appman_DATA)
 SED = sed
 
@@ -246,6 +248,7 @@ MAN_SUBSTS = \
 	-e 's|__filemansuffix__|$(FILE_MAN_SUFFIX)|g'
 
 SUFFIXES = .$(APP_MAN_SUFFIX) .man
+MAINTAINERCLEANFILES = ChangeLog
 all: config.h
 	$(MAKE) $(AM_MAKEFLAGS) all-am
 
@@ -334,6 +337,7 @@ mostlyclean-compile:
 distclean-compile:
 	-rm -f *.tab.c
 
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/xwd-clientwin.Po@am__quote@
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/xwd-dsimple.Po@am__quote@
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/xwd-list.Po@am__quote@
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/xwd-multiVis.Po@am__quote@
@@ -352,6 +356,20 @@ distclean-compile:
 @AMDEP_TRUE@@am__fastdepCC_FALSE@	source='$<' object='$@' libtool=no @AMDEPBACKSLASH@
 @AMDEP_TRUE@@am__fastdepCC_FALSE@	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) @AMDEPBACKSLASH@
 @am__fastdepCC_FALSE@	$(COMPILE) -c `$(CYGPATH_W) '$<'`
+
+xwd-clientwin.o: clientwin.c
+@am__fastdepCC_TRUE@	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(xwd_CFLAGS) $(CFLAGS) -MT xwd-clientwin.o -MD -MP -MF "$(DEPDIR)/xwd-clientwin.Tpo" -c -o xwd-clientwin.o `test -f 'clientwin.c' || echo '$(srcdir)/'`clientwin.c; \
+@am__fastdepCC_TRUE@	then mv -f "$(DEPDIR)/xwd-clientwin.Tpo" "$(DEPDIR)/xwd-clientwin.Po"; else rm -f "$(DEPDIR)/xwd-clientwin.Tpo"; exit 1; fi
+@AMDEP_TRUE@@am__fastdepCC_FALSE@	source='clientwin.c' object='xwd-clientwin.o' libtool=no @AMDEPBACKSLASH@
+@AMDEP_TRUE@@am__fastdepCC_FALSE@	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) @AMDEPBACKSLASH@
+@am__fastdepCC_FALSE@	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(xwd_CFLAGS) $(CFLAGS) -c -o xwd-clientwin.o `test -f 'clientwin.c' || echo '$(srcdir)/'`clientwin.c
+
+xwd-clientwin.obj: clientwin.c
+@am__fastdepCC_TRUE@	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(xwd_CFLAGS) $(CFLAGS) -MT xwd-clientwin.obj -MD -MP -MF "$(DEPDIR)/xwd-clientwin.Tpo" -c -o xwd-clientwin.obj `if test -f 'clientwin.c'; then $(CYGPATH_W) 'clientwin.c'; else $(CYGPATH_W) '$(srcdir)/clientwin.c'; fi`; \
+@am__fastdepCC_TRUE@	then mv -f "$(DEPDIR)/xwd-clientwin.Tpo" "$(DEPDIR)/xwd-clientwin.Po"; else rm -f "$(DEPDIR)/xwd-clientwin.Tpo"; exit 1; fi
+@AMDEP_TRUE@@am__fastdepCC_FALSE@	source='clientwin.c' object='xwd-clientwin.obj' libtool=no @AMDEPBACKSLASH@
+@AMDEP_TRUE@@am__fastdepCC_FALSE@	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) @AMDEPBACKSLASH@
+@am__fastdepCC_FALSE@	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(xwd_CFLAGS) $(CFLAGS) -c -o xwd-clientwin.obj `if test -f 'clientwin.c'; then $(CYGPATH_W) 'clientwin.c'; else $(CYGPATH_W) '$(srcdir)/clientwin.c'; fi`
 
 xwd-dsimple.o: dsimple.c
 @am__fastdepCC_TRUE@	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(xwd_CFLAGS) $(CFLAGS) -MT xwd-dsimple.o -MD -MP -MF "$(DEPDIR)/xwd-dsimple.Tpo" -c -o xwd-dsimple.o `test -f 'dsimple.c' || echo '$(srcdir)/'`dsimple.c; \
@@ -504,6 +522,9 @@ distdir: $(DISTFILES)
 	    || exit 1; \
 	  fi; \
 	done
+	$(MAKE) $(AM_MAKEFLAGS) \
+	  top_distdir="$(top_distdir)" distdir="$(distdir)" \
+	  dist-hook
 	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
 	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
 	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
@@ -633,6 +654,7 @@ distclean-generic:
 maintainer-clean-generic:
 	@echo "This command is intended for maintainers to use"
 	@echo "it deletes files that may require special tools to rebuild."
+	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
 clean: clean-am
 
 clean-am: clean-binPROGRAMS clean-generic mostlyclean-am
@@ -688,8 +710,8 @@ uninstall-am: uninstall-appmanDATA uninstall-binPROGRAMS \
 
 .PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
 	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
-	dist-gzip dist-shar dist-tarZ dist-zip distcheck distclean \
-	distclean-compile distclean-generic distclean-hdr \
+	dist-gzip dist-hook dist-shar dist-tarZ dist-zip distcheck \
+	distclean distclean-compile distclean-generic distclean-hdr \
 	distclean-tags distcleancheck distdir distuninstallcheck dvi \
 	dvi-am html html-am info info-am install install-am \
 	install-appmanDATA install-binPROGRAMS install-data \
@@ -704,6 +726,13 @@ uninstall-am: uninstall-appmanDATA uninstall-binPROGRAMS \
 
 .man.$(APP_MAN_SUFFIX):
 	sed $(MAN_SUBSTS) < $< > $@
+
+.PHONY: ChangeLog
+
+ChangeLog:
+	(GIT_DIR=$(top_srcdir)/.git git-log > .changelog.tmp && mv .changelog.tmp ChangeLog; rm -f .changelog.tmp) || (touch ChangeLog; echo 'git directory not found: installing possibly empty changelog.' >&2)
+
+dist-hook: ChangeLog
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
 .NOEXPORT:
